### ISSUE TITLE
Layout Grid: in mobile browser, tapping responsive breakpoint highlights Desktop mode by default

### ISSUE THREAD

**Issue by worldomonation** [Automattic/block-experiments#169]
### Steps to reproduce the behavior

Prereq. tested on iOS Safari.

1. Create a post.
2. Insert the Layout Grid block.
3. Tap on the edge of Layout Grid block to show options.
4. Tap on the icon that appears to be a laptop.
5. Tap on Mobile.
6. Tap on anywhere else to dismiss the dropdown.
7. Tap on the edge of Layout Grid block to show options.
8. Repeat Step 4.

#### What I expected to happen
Responsive Breakpoint dropdown will visually highlight the currently selected option. In this case, it should be `Mobile`.

#### What actually happened
Responsive Breakpoint dropdown highlights `Desktop` by default, regardless of what mode is actually selected.

### Context
Verifying fix for Automattic/wp-calypso#42148.

#### Browser / OS version
Browser: Safari
OS: iOS 14.4

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
Tested on Simple only.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - merely a visual annoyance.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/6549265/106969683-2dbdb380-6700-11eb-8665-416a29913c26.MP4

**Comment by johngodley** [comment]
> Responsive Breakpoint dropdown highlights Desktop by default, regardless of what mode is actually selected.

The highlight is the focus, not the selection. I'm not sure how this work on a mobile device but the block was updated today (after this issue was created) to show a checkmark so the difference is clearer:

![image](https://user-images.githubusercontent.com/1277682/106878592-0819b580-66d2-11eb-8db4-832894110761.png)

Can you re-test and confirm that this covers the issue here?

**Comment by jasmussen** [comment]
Yes, the blue indicator is the focus rectangle, indicating that when you press "tab" you go from desktop to tablet. This is correct practice for the web, even if it takes a little getting used to and even if the focus style is perhaps a bit more visible than we might be used to elsewhere.

But there's certainly an argument to be made where on a physical mobile device, where you obviously can't press "tab", that we might want to hide this one. I'll think about whether there's a place for such a change 👍

**Comment by simison** [comment]
@jasmussen On Calypso it's solved by focus rings showing up only on keyboard navigation: https://github.com/Automattic/wp-calypso/tree/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/lib/accessible-focus

**Comment by jasmussen** [comment]
Yep, I think there's a place for that absolutely, and especially for actual physical touch device where an external keyboard being attached would make the focus ring show up.

It's a delicate balance to handle for the core project, though, where focus even for mouse users is an indication of "here's where you clicked last". Balancing that against against [all the counterpoints of reducing visual noise](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/) is what makes great accessibility such a powerful challenge.

For this particular pattern, I find it helps to imagine using the interface with something like an Apple TV remote, using only the diagonal arrows and "confirm" button. In that setting you always need to know where you are, so you know what happens when you confirm. It's the same for sighted users, just to a slightly lesser extent.

**Comment by worldomonation** [comment]
> This is correct practice for the web, even if it takes a little getting used to and even if the focus style is perhaps a bit more visible than we might be used to elsewhere.

Interesting, I learned something today. Is there a resource I can read up on this topic some more?

**Comment by jasmussen** [comment]
There's some information and examples here: 

https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

"Correct usage" is perhaps a bit of a strong way to say it, as there is a little wiggle room. The key bit it's that when a modal dialog is opened, it should trap and loop focus until you press escape, and the focus should be visible. But that initial focus could also be on the dialog itself.

**Comment by johngodley** [comment]
@worldomonation as far as I can tell this issue was solved with the latest release, I'll close this for now but do reopen if you think there's still a problem.
