### ISSUE TITLE
Choose Layout dialog out of bounds?

### ISSUE THREAD

**Issue by oldrup** [Automattic/block-experiments#260]
Probably not the right terms, but it looks like this:

![image](https://user-images.githubusercontent.com/17141205/150511480-7c41a9fa-2d78-42f4-990b-e4b7a5d15e9d.png)

The "Choose Dialog" element almost looks like it has a negative left margin. Looks fine on the right side.

Running WordPress 5.9 RC3

First noticed in Firefox, but just confirmed in Google Chrome on my Windows 10 PC.

Are you able to reproduce?

Please let me know if you need more info.

Bjarne

**Comment by jasmussen** [comment]
Hey, thanks for the issue! From the list view it looks like you have two layout grids inserted, one that includes some content, and one that's newly inserted. Are you able to help share the full content of the page to help me debug? Just copy the contents from the code editor and share it here:
<img width="455" alt="Screenshot 2022-01-21 at 11 41 35" src="https://user-images.githubusercontent.com/1204802/150513409-f83e4a5c-d5a8-4d99-be1f-8d7697df9488.png">

If you need to fuzzy up private content that's perfectly fine, it's just for debugging. Also if you can share which theme you are testing with, that can help as well. 

There's an issue in #249 which has been hard to debug, but could possibly be related.

**Comment by oldrup** [comment]
Sure! Thank you for looking into this. I'm quite intrigued by the Grid Layout block.

I think the issue is related to the default Full Width state of the block... Have a look at this screencast:
https://watch.screencastify.com/v/JpGjTtQJ5epVW6dkxud7

I'm using the Blocksy theme from https://wordpress.org/themes/blocksy/

Here's the code for a test page made for the purpose of troublehooting:
`
<section class="wp-block-group has-palette-color-6-background-color has-background">
<h2 id="this-is-a-heading-in-a-section">This is a heading in a section</h2>



<p>Tortor congue erat molestie tempus eget sollicitudin massa orci massa hendrerit hendrerit placerat felis orci magna magna a nunc et fusce tincidunt dolor elementum scelerisque.</p>



<div class="wp-block-jetpack-layout-grid column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3">
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none">
<h3 id="grid-col-1">Grid col 1</h3>



<p>Accumsan fusce leo quis eu id interdum nisi eros tincidunt ut tincidunt ipsum metus purus tortor placerat ex leo facilisis consectetur arcu pellentesque sem euismod.</p>
</div>



<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none">
<h3 id="grid-col-2">Grid col 2</h3>



<p>Purus arcu adipiscing ac felis sit rutrum massa gravida urna dolor massa enim id bibendum pellentesque portaest euismod tristique massa consectetur suspendisse a commodo mi.</p>
</div>



<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none">
<h3 id="grid-col-3">Grid col 3</h3>



<p>Condimentum phasellus quisque amet quis euismod leo scelerisque elit sit varius vivamus sem lorem fusce suspendisse scelerisque tempus portaest fusce facilisis facilisis lorem maximus nisl.</p>
</div>
</div>
</section>
`

Ley me know if theres anything else I can do to help troubleshoot.

And let me say, this is purely a back end UX issue. The Grid looks fine as expected on the front end.

/Bjarne

**Comment by jasmussen** [comment]
Thank you, that was very helpful! The content you had appeared to work well enough for me:
![initial](https://user-images.githubusercontent.com/1204802/150527818-b8158a6e-618b-4f44-b7dd-77d5e0680f2b.gif)

But your screencast was very helpful in narrowing down the problem, and I was able to reproduce:

<img width="1392" alt="Screenshot 2022-01-21 at 13 31 12" src="https://user-images.githubusercontent.com/1204802/150527875-71896e68-7a20-4620-a5c0-25caec7f99bd.png">

It appears to be a conflict with with how blocksy handles full-width blocks. Here's a short GIF where I find two negative margin styles that appear to be causing a bit of messiness:
![inspectors](https://user-images.githubusercontent.com/1204802/150528092-69f6ea28-0201-47df-b3ce-e70cd13f1de5.gif)

From what I can tell those negative margins (-10px on both sides) are there to compensate for the canvas padding (10px all around) so that blocks go truly full-width, which is perfectly fair, and a `width: 100%;` rule on the layout grid side is causing the math to go wrong. I'll think about whether and how we can push a fix on the layout grid side to be a bit more flexible in full-width scenarios, but in the mean time you could add this CSS to work around the issue, which appears to be editor-only:

```
.ct-theme-editor-styles .wp-block[data-align=full] {
	width: auto;
}
```

That would get you this:
<img width="1392" alt="Screenshot 2022-01-21 at 13 39 45" src="https://user-images.githubusercontent.com/1204802/150528907-5635a4ce-7bc5-4976-82f4-712968331721.png">
<img width="1392" alt="Screenshot 2022-01-21 at 13 39 48" src="https://user-images.githubusercontent.com/1204802/150528911-518730ac-fdee-448a-8858-3f4361517e8b.png">

Not perfect, but at least representative of the negative margins.

**Comment by oldrup** [comment]
Well, thank you! That's very useful feedback. I've taken it to the developers of Blocksy. Being a block oriented theme, supporting a wide range of 3rd party block plugins, I'm convinced that they find an interest in looking into this.

The Grid still appears to work fine on the frontend, so it's now a showstopper. 

Thank you again, @jasmussen
