### ISSUE TITLE
Layout Grid: No visible + sign when adding a new block, Conflicting with Gutenberg Plugin

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/block-experiments#91]
Originally reported on https://github.com/Automattic/wp-calypso/issues/42540 and 9F6qB-p2

It appears that there are issues adding new blocks within an existing layout grid. There's also a conflict between the Gutenberg plugin and Layout Grid regarding styling as discovered by @edequalsawesome 

> .wp-block:not(.is-selected):not(.has-child-selected) .block-editor-default-block-appender {
    display:none
}

@serabi's notes:

#### Steps to reproduce

1. Add a Layout Grid block to the page. 
2. Add a content block (such as an Paragraph or video block) at the top of the first Layout Grid column
3. Try to add a second block, below the first block. There is no plus sign. To add the second block, you need to hit enter or click on the block you've already added and select the option to add before or add after, or you need to click in the exact spot the plus sign would be, if it is visible. 

Deactivating the Gutenberg plugin seems to help at this time. 

#### Screenshot / Video

![Test Site](https://d.pr/i/UW5puN+)

#### Context / Source

#user-report - see 2992383-zen

Internal discussion on Atomic Requests: 9F6qB-p2

**Comment by johngodley** [comment]
As far as I know this is how Gutenberg works. You can see the same effect in the core columns block where adding a pagragraph to a column does not show the inserter inside the column.

![image](https://user-images.githubusercontent.com/1277682/84013370-bcf7a900-a970-11ea-9e4b-cdfc795b7827.png)

Additionally, the above CSS is not part of the layout grid.

@jasmussen can you confirm this is expected behaviour?
